name: Lerna Publish Alpha

on:
  pull_request:
    branches:
      - feature/**
    types: [opened, synchronize]

jobs:
  publish_feat:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version: '12.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions

      - run: yarn install
      - name: 'Publish prerelease to NPM'
        run: yarn lerna publish --conventional-prerelease --dist-tag alpha --yes --preid alpha
        # run: yarn lerna publish prerelease --yes --preid feat --force-publish --dist-tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
